dist: xenial
sudo: true
language: python
python:
  - 3.6.5
services:
- docker
install:

- wget -O llvm-snapshot.gpg.key https://apt.llvm.org/llvm-snapshot.gpg.key 
- sudo apt-key add llvm-snapshot.gpg.key
- sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
- sudo apt-get -y update
- sudo apt-get -y install build-essential gcc-multilib clang-6.0 cmake python3-pip python3-setuptools libffi-dev python3-nose
- pip3 install pip
- pip3.6 -V
- pip3.6 install pyflakes
- pip3.6 install z3-solver
- pip3.6 install angr
- pip3.6 install git+git://github.com/trailofbits/manticore.git
- mkdir build
- cd build
- CC=clang-6.0 CXX=clang++-6.0 cmake ..
- sudo make install
- cd ..
env:
- TASK=CRASH
- TASK=FIXTURE
- TASK=KLEE
- TASK=LISTS
- TASK=ONEOF
- TASK=OVERFLOW
#- TASK=PRIMES
- TASK=RUNLEN
#- TASK=STREAMINGANDFORMATTING
- TASK=TAKEOVER
- TASK=BORINGDISABLED
script:
- pyflakes bin/deepstate/*.py
- pyflakes tests/*.py
- if [ $TASK = CRASH ]; then nosetests3 tests/test_crash.py ; fi
- if [ $TASK = FIXTURE ]; then nosetests3 tests/test_fixture.py ; fi
- if [ $TASK = KLEE ]; then nosetests3 tests/test_klee.py ; fi
- if [ $TASK = LISTS ]; then nosetests3 tests/test_lists.py ; fi
- if [ $TASK = ONEOF ]; then nosetests3 tests/test_oneof.py ; fi
- if [ $TASK = RUNLEN ]; then nosetests3 tests/test_runlen.py ; fi
- if [ $TASK = OVERFLOW ]; then nosetests3 tests/test_overflow.py ; fi
- if [ $TASK = PRIMES ]; then nosetests3 tests/test_primes.py ; fi
#- if [ $TASK = STREAMINGANDFORMATTING ]; then nosetests3 tests/test_streamingandformatting.py ; fi
- if [ $TASK = TAKEOVER ]; then nosetests3 tests/test_takeover.py ; fi
#- if [ $TASK = BORINGDISABLED ]; then nosetests3 tests/test_boringdisabled.py ; fi
after_success:
- travis_wait bash push/run.sh

