name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes mypy
      - name: Lint
        run: |
          find ./bin -name '*.py' -exec pyflakes "{}" \;
          find ./tests -name '*.py' -exec pyflakes "{}" \;
          mypy --strict-optional --config-file mypy.ini bin/deepstate
  build:
    strategy:
      matrix:
        env:
          - TEST: crash
          - TEST: fixture
          - TEST: klee
          - TEST: lists
          - TEST: oneof
          - TEST: runlen
          - TEST: runlen
          - TEST: overflow
          - TEST: primes
          - TEST: takeover
          # - TEST: streamingandformatting
          # - TEST: boringdisabled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          sudo apt install build-essential gcc-multilib cmake libffi-dev
          python -m pip install --upgrade pip
          pip install z3-solver angr nose
          pip install git+git://github.com/trailofbits/manticore.git
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          sudo make install
      - name: Test
        run: |
          nosetests tests/test_${{ matrix.env.TEST }}.py
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build deepstate-base image locally
        run: |
          docker build -t deepstate-base -f docker/base/Dockerfile docker/base
      - name: Build and publish container
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: trailofbits/deepstate/deepstate
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile
          tag_names: true
          cache: ${{ github.event_name != 'schedule' }}
